services:
  api:
    image: mcsystems/news-search-api:${IMAGE_TAG}
    build: .
    ports:
      - 8000:8000
    networks:
      - new-search-api
    volumes:
      - .:/app

  ui:
    image: mcsystems/news-search-api:${IMAGE_TAG}
    build: .
    environment:
      APIURL: http://api:8000/v1
    ports:
      - 8501:8501
    networks:
      - new-search-api
    volumes:
      - .:/app
    depends_on:
      - api
    command: streamlit run ui.py

networks:
  new-search-api:
    name: new-search-api
