name: Build Docker Image for Every Tag

on:
  push:
    branches:
      - 'staging'
    tags:
      - '**'
env:
    IMAGE_NAME: "codeforafrica/news-search-api"
    BETA_VERSION: "b1"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Version
        uses: actions/checkout@v4

      - name: Dump tag name
        run: echo "Building ${{ github.ref_type }} ${{ github.ref_name }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=staging-${{ env.BETA_VERSION }},enable=${{ endsWith(github.ref, 'staging') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #registry defaults to dockerhub
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
