name: Lint Code

on:
  - push
  - pull_request

jobs:
  lint:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    name: Lint in Docker
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: ./Dockerfile
