name: Lint Code

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint in Docker
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: ./Dockerfile
