name: Repo Sync

on: 
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync GitLab Repo
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: https://git.archive.org/wb/web_collection_search.git
        target-username: sawood
        target-token: ${{ secrets.GITLAB_TOKEN }}
